# The base hadoop image to use for all components.
# See this repo for image build details: https://github.com/Comcast/kube-yarn/tree/master/image
image: jwgumcz/bench
imagePullPolicy: IfNotPresent

# The version of the hadoop libraries being used in the image.
hadoopVersion: 2.7.3

# Select antiAffinity as either hard or soft, default is soft
antiAffinity: "soft"

mysql: 
  name: hello-world-sql
  mysqlRootPassword: "a"
  mysqlUser: "hive"
  mysqlPassword: "phive"
  mysqlDatabase: "metastore_db"
  
abench:
  replicas: 1
  driver:
    pdbMinAvailable: 1
    resources:
      requests:
        memory: "1G"
        cpu: "10m"
      limits:
        memory: "2048Mi"
        cpu: "1000m"

spark_master: 
  replicas: 1
  resources:
      requests:
        memory: "256Mi"
        cpu: "10m"
      limits:
        memory: "2048Mi"
        cpu: "1000m"
  DaemonMemory: "1g"
  ServicePort: "7077"
  ContainerPort: "9005"

spark_worker:
  replicas: 2
  resources:
      requests:
        memory: "1G"
        cpu: "10m"
      limits:
        memory: "2048Mi"
        cpu: "1000m"
  DaemonMemory: "1g"
  ExecutorMemory: "1g"
  ContainerPort: 9006

hdfs:
  nameNode:
    pdbMinAvailable: 1
    resources:
      requests:
        memory: "256Mi"
        cpu: "10m"
      limits:
        memory: "2048Mi"
        cpu: "1000m"

  dataNode:
    replicas: 1
    pdbMinAvailable: 1
    resources:
      requests:
        memory: "256Mi"
        cpu: "10m"
      limits:
        memory: "2048Mi"
        cpu: "1000m"

yarn:
  resourceManager:
    pdbMinAvailable: 1

    resources:
      requests:
        memory: "256Mi"
        cpu: "10m"
      limits:
        memory: "2048Mi"
        cpu: "2000m"

  nodeManager:
    pdbMinAvailable: 1

    # The number of YARN NodeManager instances.
    replicas: 2

    # Create statefulsets in parallel (K8S 1.7+)
    parallelCreate: false

    # CPU and memory resources allocated to each node manager pod.
    # This should be tuned to fit your workload.
    resources:
      requests:
        memory: "1048Mi"
        cpu: "10m"
      limits:
        memory: "2048Mi"
        cpu: "1000m"

persistence:
  nameNode:
    enabled: false
    storageClass: "-"
    accessMode: ReadWriteOnce
    size: 50Gi

  dataNode:
    enabled: false
    storageClass: "-"
    accessMode: ReadWriteOnce
    size: 200Gi
